// This file is @generated by prost-build.
/// 传输数据的指令类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CmdType {
    /// /// 通用
    ///
    /// 心跳检测
    Heartbeat = 0,
    /// 认证
    Auth = 1,
    /// 认证通过
    AuthOk = 2,
    /// 认证失败
    AuthErr = 3,
    /// 连接
    Connect = 4,
    /// 断开连接
    Disconnect = 5,
    /// 数据传输
    Transfer = 6,
    /// 开启代理端口
    OpenServer = 7,
    /// 关闭代理端口
    CloseServer = 8,
}
impl CmdType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Heartbeat => "HEARTBEAT",
            Self::Auth => "AUTH",
            Self::AuthOk => "AUTH_OK",
            Self::AuthErr => "AUTH_ERR",
            Self::Connect => "CONNECT",
            Self::Disconnect => "DISCONNECT",
            Self::Transfer => "TRANSFER",
            Self::OpenServer => "OPEN_SERVER",
            Self::CloseServer => "CLOSE_SERVER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HEARTBEAT" => Some(Self::Heartbeat),
            "AUTH" => Some(Self::Auth),
            "AUTH_OK" => Some(Self::AuthOk),
            "AUTH_ERR" => Some(Self::AuthErr),
            "CONNECT" => Some(Self::Connect),
            "DISCONNECT" => Some(Self::Disconnect),
            "TRANSFER" => Some(Self::Transfer),
            "OPEN_SERVER" => Some(Self::OpenServer),
            "CLOSE_SERVER" => Some(Self::CloseServer),
            _ => None,
        }
    }
}
