// This file is @generated by prost-build.
/// 传输数据的消息定义
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferMessageMetaData {
    /// 时间戳
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// 元数据
    #[prost(map = "string, string", tag = "2")]
    pub meta_data: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
