// This file is @generated by prost-build.
/// 传输数据的消息定义
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferDataMessage {
    #[prost(enumeration = "super::cmd_type::CmdType", tag = "1")]
    pub cmd_type: i32,
    #[prost(message, optional, tag = "2")]
    pub meta_data: ::core::option::Option<super::meta_data::TransferMessageMetaData>,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
